stages:
  - development
  - test
install angular support:
  image: node:current-alpine
  stage: development
  script:
    - npm ci
testing angular:
  image: node:current-alpine
  stage: test
  script:
    - npm ci
    - npm run test -- --no-watch --no-progress --browsers= FirefoxHeadless
